name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint flake8 flake8-docstrings
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Run shellcheck
      run: shellcheck --severity=error --external-sources hamclock-update.sh

    - name: Run black
      run: black --check .

    - name: Run pylint
      run: pylint update_server.py

    - name: Run flake8
      run: flake8 --max-line-length=90 update_server.py

    - name: Run checks
      run: |
        black --check update_server.py
        pylint update_server.py
        flake8 --max-line-length=80 update_server.py
